### ISSUE TITLE
view dataset data link throws an error

### ISSUE THREAD

**Issue by ScottMaxson** [seabourne/nxus-dataset#9]
```
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:  Tue, 20 Dec 2016 02:51:15 GMT nxus:data-set-admin:debug editing dataset id:   582cf7be1933d43772a690fd 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:  Tue, 20 Dec 2016 02:51:15 GMT nxus:templater-ejs:error Error rendering inline partial Error: Template name included-imports not found 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:  ___Stack trace #1___ 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:  Error: Template name included-imports not found 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Templater.render (/app/node_modules/nxus-templater/lib/index.js:305:41) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at /app/node_modules/nxus-core/lib/Dispatcher.js:183:31 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Array.map (native) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at /app/node_modules/nxus-core/lib/Dispatcher.js:182:36 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:604:10) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:143:12) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at runCallback (timers.js:574:20) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at tryOnImmediate (timers.js:554:5) 
Dec 19 18:51:16 seabourne-wpsp-staging app/web.1:      at processImmediate [as _immediateCallback] (timers.js:533:5) 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/assets/css/timeline.css" host=seabourne-wpsp-staging.herokuapp.com request_id=9ca82bd0-9341-40d2-b1f7-24428ecd3c4d fwd="71.217.78.125" dyno=web.1 connect=1ms service=25ms status=304 bytes=395 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/admin/datasets-dataset/edit/582cf7be1933d43772a690fd" host=seabourne-wpsp-staging.herokuapp.com request_id=665aae72-bc6c-415f-99d4-f49632715aca fwd="71.217.78.125" dyno=web.1 connect=1ms service=54ms status=200 bytes=3255 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/admin/assets/vendor/metisMenu/metisMenu.min.js" host=seabourne-wpsp-staging.herokuapp.com request_id=05f9d43e-0328-44dd-bad6-3c72f7ffd4a7 fwd="71.217.78.125" dyno=web.1 connect=1ms service=57ms status=304 bytes=395 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/assets/bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0" host=seabourne-wpsp-staging.herokuapp.com request_id=708f7c7f-ce9c-48ab-bc00-f34f61c09369 fwd="71.217.78.125" dyno=web.1 connect=1ms service=60ms status=304 bytes=396 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/assets/bower_components/metisMenu/dist/metisMenu.min.css" host=seabourne-wpsp-staging.herokuapp.com request_id=075afcb1-cd8e-4fdd-be44-1da7d7f4a0f0 fwd="71.217.78.125" dyno=web.1 connect=1ms service=28ms status=304 bytes=395 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/admin/assets/vendor/jquery/jquery.min.js" host=seabourne-wpsp-staging.herokuapp.com request_id=19e652f4-7bec-428f-8c8a-ab9763ca64d8 fwd="71.217.78.125" dyno=web.1 connect=1ms service=61ms status=304 bytes=397 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/assets/bower_components/morrisjs/morris.css" host=seabourne-wpsp-staging.herokuapp.com request_id=243933be-8020-44e1-a16c-9036b47ac391 fwd="71.217.78.125" dyno=web.1 connect=1ms service=23ms status=304 bytes=395 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/assets/css/sb-admin-2.css" host=seabourne-wpsp-staging.herokuapp.com request_id=b971448b-0223-480c-8b91-87f40cbb2840 fwd="71.217.78.125" dyno=web.1 connect=1ms service=29ms status=304 bytes=396 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/admin/assets/vendor/bootstrap/js/bootstrap.min.js" host=seabourne-wpsp-staging.herokuapp.com request_id=eb271b70-22f4-4ce3-8162-99b88ec83877 fwd="71.217.78.125" dyno=web.1 connect=1ms service=59ms status=304 bytes=396 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/assets/bower_components/bootstrap/dist/css/bootstrap.min.css" host=seabourne-wpsp-staging.herokuapp.com request_id=863f65c8-3a96-4822-b890-173a895eff07 fwd="71.217.78.125" dyno=web.1 connect=1ms service=19ms status=304 bytes=397 
Dec 19 18:51:16 seabourne-wpsp-staging heroku/router:  at=info method=GET path="/admin/assets/js/sb-admin-2.js" host=seabourne-wpsp-staging.herokuapp.com request_id=52690bc4-6141-4e22-9876-a894c8248ecb fwd="71.217.78.125" dyno=web.1 connect=1ms service=56ms status=304 bytes=395  
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:  Unhandled rejection ReferenceError: /app/node_modules/nxus-dataset/lib/controllers/../templates/datasets-dataset-detail.ejs:14 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      12|   <thead>  
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      13|    <tr>  
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:   >> 14|     <% if (dataset.fields) {  
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      15|        fields.forEach((field) => {   
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      16|         if (field.isVisible) {  
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      17|          var fldName = (field.label ? field.label : morph.toTitle(field.name))  
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:  dataset is not defined 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at eval (eval at compile (/app/node_modules/ejs/lib/ejs.js:498:12), <anonymous>:20:12) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at returnedFn (/app/node_modules/ejs/lib/ejs.js:529:17) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Object.exports.render (/app/node_modules/ejs/lib/ejs.js:339:37) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at /app/node_modules/nxus-templater/lib/modules/renderer-ejs/index.js:64:30 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:604:10) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:143:12) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:148:10) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at runCallback (timers.js:574:20) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at tryOnImmediate (timers.js:554:5) 
Dec 19 18:51:24 seabourne-wpsp-staging app/web.1:      at processImmediate [as _immediateCallback] (timers.js:533:5) 
Dec 19 18:51:54 seabourne-wpsp-staging heroku/router:  at=error code=H12 desc="Request timeout" method=GET path="/data-set-view/view/582cf7be1933d43772a690fd" host=seabourne-wpsp-staging.herokuapp.com request_id=5e4fd84e-0c87-446e-b4f8-817fb7edd656 fwd="71.217.78.125" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0 
```

**Comment by ScottMaxson** [comment]
this has been fixed by recent updates and published.
